name:                haskell-project-template
version:             0.1.0.0
github:              srdqty/haskell-project-template
license:             BSD3
author:              Sofia Donataccio
maintainer:          srdqty@gmail.com
copyright:           Copyright (c) 2018 Sofia Donataccio

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:
# description:
# category:            Web

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options:
    - -Wall

executables:
  haskell-project-template:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
    dependencies:
      - haskell-project-template

tests:
  haskell-project-template-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
    dependencies:
      - haskell-project-template
      - hspec
