name:                haskell-project-template
version:             0.1.0.0
github:              srdqty/haskell-project-template
license:             BSD3
author:              Sofia Donataccio
maintainer:          srdqty@gmail.com
copyright:           Copyright (c) 2018 Sofia Donataccio

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:
# description:
# category:            Web

flags:
  dump-ghc-core:
    description: Dump ghc-core to file when compiling
    manual: true
    default: false

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src
  when:
  - condition: flag(dump-ghc-core)
    then:
      ghc-options:
        - -Wall
        - -O2
        - -ddump-simpl
        - -ddump-to-file
    else:
      ghc-options:
        - -Wall
        - -O2

executables:
  haskell-project-template:
    main: Main.hs
    source-dirs: app
    when:
    - condition: flag(dump-ghc-core)
      then:
        ghc-options:
          - -threaded
          - -rtsopts
          - -with-rtsopts=-N
          - -Wall
          - -O2
          - -ddump-simpl
          - -ddump-to-file
      else:
        ghc-options:
          - -threaded
          - -rtsopts
          - -with-rtsopts=-N
          - -Wall
          - -O2
    dependencies:
      - haskell-project-template

tests:
  haskell-project-template-test:
    main: Spec.hs
    source-dirs: test
    when:
    - condition: flag(dump-ghc-core)
      then:
        ghc-options:
          - -threaded
          - -rtsopts
          - -with-rtsopts=-N
          - -Wall
          - -O2
          - -ddump-simpl
          - -ddump-to-file
      else:
        ghc-options:
          - -threaded
          - -rtsopts
          - -with-rtsopts=-N
          - -Wall
          - -O2
    dependencies:
      - haskell-project-template
      - hspec
